### ISSUE TITLE
Script Not Readable

### ISSUE THREAD

**Issue by itscory** [motoxnate/El-Disk-Utility#1]
On a fresh installation of El Capitan, I got this error message upon launching:

> Title: Can't get 1.
> Message: Finder got an error: Can't get 1. (-1728)

I tried to open the script in script editor to find out why it was doing this, but it has been saved as run-only and I cannot edit or view it. Could you save the .scpt file as editable and upload it?

**Comment by motoxnate** [comment]
Thanks for your inquiry!
This issue sounds familiar to me for some reason. I am currently away on a college visit, but I'll upload a script file when I get home!

**Comment by itscory** [comment]
Thank you! I also opened the script with text editor. It's hard to read without using script editor, but I think I see references to the volume "Macintosh HD". It doesn't seem to be related to my original issue (I tried renaming mine to Macintosh HD and still get the error), but if it does indeed reference the volume by name, people not using that volume name might not be able to run it.

All-in-all, I'm very interested in your script and I'd love to help make something better out of it. :smiley:

**Comment by motoxnate** [comment]
If I remember correctly, I was careful not to use any volume names because I knew it would not be cross compatible with other systems. I used a combination of shell scripts running inside the apple script to get the drive names at disk0 disk1 etc.
Unfortunately I believe my only copy of the program is currently at work, so the soonest I can get it is Tuesday. 
I love the support and I'm very grateful you're interested in helping!
I'll get that script on here soon and we'll see what we can make of this issue. 
-Nate

**Comment by motoxnate** [comment]
@itscory I uploaded the script if you'd like to take a look.

**Comment by itscory** [comment]
Perfect! Thank you!
